//
// Supplies the machine-level configuration files that System.Web's configuration system needs.
//
// On .NET Framework these live next to the framework (machine.config plus the root web.config in
// the same directory) and WebConfigurationHost finds them through
// RuntimeEnvironment.SystemConfigurationFile. That API throws PlatformNotSupportedException on
// .NET Core, so tools/port-patches.txt redirects those reads to PortPaths.MachineConfigPath, which
// delegates here.
//
// The two files are embedded resources generated by tools/gen-config.ps1 from
// mono/data/net_4_5/{machine.config,web.config}, with strong-name qualification stripped (this
// port's System.Web is unsigned and can never satisfy PublicKeyToken=b03f5f7f11d50a3a). They are
// extracted to a per-application directory on first use, so an application needs nothing installed
// machine-wide and two applications never share a config directory.
//
// Why the root web.config matters: it carries the default <httpHandlers> (which is what maps
// *.aspx to PageHandlerFactory), <httpModules>, <pages>, <compilation> and <buildProviders>
// registrations. Without it nothing is served at all.
//

using System;
using System.IO;
using System.Reflection;

namespace System.Web.Util
{
	static class MachineConfig
	{
		const string MachineResource = "System.Web.Config.machine.config";
		const string RootWebResource = "System.Web.Config.root-web.config";
		// machine.config's <wsdlHelpGenerator href="DefaultWsdlHelpGenerator.aspx"/> is resolved
		// relative to this directory, so the .asmx help page is extracted with the config files.
		const string WsdlHelpResource = "System.Web.Config.DefaultWsdlHelpGenerator.aspx";

		static readonly object sync = new object ();
		static string machine_config_path;

		// Full path to the extracted machine.config. Its directory also holds the root web.config,
		// which is how WebConfigurationHost.GetStreamName locates it (MachineWebPath resolves to
		// GetWebConfigFileName (directory of machine.config)).
		internal static string Path {
			get {
				if (machine_config_path != null)
					return machine_config_path;

				lock (sync) {
					if (machine_config_path == null)
						machine_config_path = Extract ();
					return machine_config_path;
				}
			}
			// Lets a host point at its own curated configuration instead.
			set {
				lock (sync)
					machine_config_path = value;
			}
		}

		static string Extract ()
		{
			string dir = System.IO.Path.Combine (ConfigDirectoryRoot (), "config");
			Directory.CreateDirectory (dir);

			string machine = System.IO.Path.Combine (dir, "machine.config");
			string rootWeb = System.IO.Path.Combine (dir, "web.config");

			WriteResource (MachineResource, machine);
			WriteResource (RootWebResource, rootWeb);
			WriteResource (WsdlHelpResource, System.IO.Path.Combine (dir, "DefaultWsdlHelpGenerator.aspx"));

			return machine;
		}

		static string ConfigDirectoryRoot ()
		{
			// Sits beside the codegen directory, keyed on the same application discriminator, so
			// everything this port generates for one application lives under one root.
			string dynamicBase = PortPaths.DynamicBase;
			string parent = System.IO.Path.GetDirectoryName (dynamicBase);
			return String.IsNullOrEmpty (parent) ? dynamicBase : parent;
		}

		static void WriteResource (string resourceName, string destination)
		{
			Assembly self = typeof (MachineConfig).Assembly;
			using (Stream source = self.GetManifestResourceStream (resourceName)) {
				if (source == null)
					throw new InvalidOperationException (String.Format (
						"Embedded configuration resource '{0}' is missing from {1}. It is generated " +
						"by tools/gen-config.ps1 and embedded by Core.Web.csproj.",
						resourceName, self.GetName ().Name));

				// Rewrite every time: an upgraded System.Web must not keep serving a stale
				// configuration extracted by a previous version.
				byte [] content = new byte [source.Length];
				int read, offset = 0;
				while (offset < content.Length &&
				       (read = source.Read (content, offset, content.Length - offset)) > 0)
					offset += read;

				if (File.Exists (destination) && SameContent (destination, content))
					return;

				File.WriteAllBytes (destination, content);
			}
		}

		static bool SameContent (string path, byte [] expected)
		{
			try {
				byte [] existing = File.ReadAllBytes (path);
				if (existing.Length != expected.Length)
					return false;
				for (int i = 0; i < existing.Length; i++)
					if (existing [i] != expected [i])
						return false;
				return true;
			} catch (IOException) {
				return false;
			}
		}
	}
}
