//
// The embedded machine.config / root-web.config that Port/MachineConfig.cs extracts at runtime.
//
// These are generated by Tools/gen-config.ps1 from Mono's shipped configuration and rewritten so
// they name this port's assemblies. Getting that wrong does not fail loudly - it produces 404s on
// *.aspx, or a 500 at application start - so the retargeting is asserted here directly.
//

using System;
using System.IO;
using Xunit;

namespace WebFormsPort.ConfigurationTests
{
	[Collection (ConfigurationCollection.Name)]
	public class MachineConfigTests
	{
		readonly ConfigurationFixture fixture;

		public MachineConfigTests (ConfigurationFixture fixture)
		{
			this.fixture = fixture;
		}

		[Fact]
		public void Machine_config_is_extracted_to_disk ()
		{
			Assert.NotNull (fixture.MachineConfigPath);
			Assert.True (File.Exists (fixture.MachineConfigPath),
				     "machine.config was not extracted to " + fixture.MachineConfigPath);
		}

		[Fact]
		public void Root_web_config_is_extracted_alongside_it ()
		{
			Assert.NotNull (fixture.RootWebConfigPath);
			Assert.True (File.Exists (fixture.RootWebConfigPath),
				     "root web.config was not extracted to " + fixture.RootWebConfigPath);
		}

		[Fact]
		public void Wsdl_help_generator_is_extracted_next_to_machine_config ()
		{
			// machine.config's <wsdlHelpGenerator href="DefaultWsdlHelpGenerator.aspx"/> resolves
			// relative to the machine config directory, so browsing an .asmx without ?wsdl needs it
			// to be there.
			string directory = Path.GetDirectoryName (fixture.MachineConfigPath);

			Assert.True (File.Exists (Path.Combine (directory, "DefaultWsdlHelpGenerator.aspx")),
				     "DefaultWsdlHelpGenerator.aspx was not extracted next to machine.config");
		}

		[Fact]
		public void Root_web_config_maps_aspx_to_the_page_handler_factory ()
		{
			string text = File.ReadAllText (fixture.RootWebConfigPath);

			// Without this registration nothing is served at all.
			Assert.Contains ("*.aspx", text);
			Assert.Contains ("PageHandlerFactory", text);
		}

		[Fact]
		public void Generated_config_carries_no_strong_name_qualification ()
		{
			string text = Uncommented (fixture.MachineConfigPath) + Uncommented (fixture.RootWebConfigPath);

			// This port is unsigned and can never satisfy "PublicKeyToken=b03f5f7f11d50a3a", so
			// gen-config.ps1 strips it. A surviving reference binds to nothing at runtime.
			Assert.DoesNotContain ("PublicKeyToken=b03f5f7f11d50a3a", text);
			Assert.DoesNotContain ("Version=4.0.0.0", text);
		}

		[Fact]
		public void Assembly_references_name_the_ported_assemblies ()
		{
			string text = Uncommented (fixture.RootWebConfigPath);

			// assembly="System.Web" would resolve to the EMPTY framework facade, silently dropping
			// the WebParts tag prefix and a compile-time reference.
			Assert.DoesNotContain ("assembly=\"System.Web\"", text);
			Assert.DoesNotContain ("assembly=\"System.Configuration\"", text);
		}

		/// <summary>
		/// File contents with XML comments removed. The generator writes a header explaining what it
		/// stripped, and gen-config.ps1 comments out entries naming unshipped assemblies rather than
		/// deleting them - so the strings these tests forbid legitimately appear inside comments,
		/// where they are inert.
		/// </summary>
		static string Uncommented (string path)
		{
			return System.Text.RegularExpressions.Regex.Replace (
				File.ReadAllText (path), "<!--.*?-->", String.Empty,
				System.Text.RegularExpressions.RegexOptions.Singleline);
		}

		[Fact]
		public void Extensions_registrations_are_retargeted_at_the_ported_assembly ()
		{
			string text = File.ReadAllText (fixture.RootWebConfigPath);

			// ScriptModule is an <httpModules> entry, instantiated at application start - if this
			// still said System.Web.Extensions every request would fail with FileNotFoundException.
			Assert.Contains ("Core.Web.Extensions", text);
			Assert.DoesNotContain (", System.Web.Extensions\"", text);
		}
	}
}
