//------------------------------------------------------------------------------
// <auto-generated>
//     Control field declarations for Session.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotingSample
{
	public partial class SessionPage
	{
		protected global::System.Web.UI.WebControls.Literal Mode;
		protected global::System.Web.UI.WebControls.Literal Id;
		protected global::System.Web.UI.WebControls.Literal Result;
		protected global::System.Web.UI.WebControls.Literal Hits;
		protected global::System.Web.UI.WebControls.Literal Pid;
	}
}
