//
// Razor view rendering, driven by a real browser.
//
// Views reach the response through: RazorBuildProvider compiling the .cshtml at request time, the
// Razor host resolved from <system.web.webPages.razor><host factoryType="..."/>, the generated class
// deriving from WebViewPage, and the view engine locating the file through BuildManager.
//
// That whole path was dead until BuildManager.GetType was fixed to match an assembly reference on its
// simple name: the host factory could not be resolved, so every view failed to compile, and because
// BuildManager.GetObjectFactory swallows compile exceptions it surfaced as "the view was not found"
// rather than as the real error. These are the regression net for that.
//

using System.Threading.Tasks;
using Microsoft.Playwright;
using Xunit;

namespace WebFormsPort.MvcBrowserTests
{
	[Collection (MvcBrowserCollection.Name)]
	public class RazorViewBrowserTests
	{
		readonly MvcBrowserFixture fixture;

		public RazorViewBrowserTests (MvcBrowserFixture fixture)
		{
			this.fixture = fixture;
		}

		[Fact]
		public async Task View_renders_through_its_layout ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				IResponse response = await page.GotoAsync ("/");

				Assert.Equal (200, response.Status);

				// The layout wraps the view, and @RenderBody put the view between the two.
				Assert.Equal ("[layout header]", await page.InnerTextAsync ("#chrome-header"));
				Assert.Equal ("[layout footer]", await page.InnerTextAsync ("#chrome-footer"));
				Assert.Equal ("Widgets", await page.InnerTextAsync ("h1"));
			}
		}

		[Fact]
		public async Task Layout_title_comes_from_ViewBag ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/");

				// The view sets ViewBag.Title; the LAYOUT reads it - so this is state crossing from
				// view to layout, not just a value rendered where it was set.
				Assert.Equal ("Index - MVC on Kestrel", await page.TitleAsync ());
			}
		}

		[Fact]
		public async Task Strongly_typed_model_is_enumerated_in_the_view ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/");

				// @model IEnumerable<Widget> plus a @foreach over it.
				Assert.Equal (3, await page.Locator ("#widgets tr").CountAsync ());
				Assert.Equal ("3", await page.InnerTextAsync ("#count"));
				Assert.Contains ("sprocket", await page.InnerTextAsync ("#widgets"));
				Assert.Contains ("24.50", await page.InnerTextAsync ("#widgets"));
			}
		}

		[Fact]
		public async Task Section_defined_by_the_view_is_rendered_by_the_layout ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/");

				// @section Footer in the view, @RenderSection in the layout, guarded by
				// IsSectionDefined - so this covers the section machinery rather than plain output.
				Assert.Equal ("[index section]", await page.InnerTextAsync ("#section-footer"));
			}
		}

		[Fact]
		public async Task Html_ActionLink_generates_a_route_based_url ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/");

				// Generated by the routing table, not written literally in the view.
				string href = await page.Locator ("#widgets a").First.GetAttributeAsync ("href");

				Assert.Equal ("/Home/Details/1", href);
			}
		}

		[Fact]
		public async Task Following_a_generated_link_binds_the_route_parameter ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/");
				await page.Locator ("#widgets a").Nth (1).ClickAsync ();
				await page.WaitForLoadStateAsync ();

				// {id} came out of the URL and was bound to the action's int parameter.
				Assert.Contains ("/Home/Details/2", page.Url);
				Assert.Equal ("2 / flange / 24.50", await page.InnerTextAsync ("#detail"));
			}
		}

		[Fact]
		public async Task Razor_html_encodes_by_default ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/Home/Details/1");

				// The view writes a literal "<script>alert(1)</script>". Razor must encode it, so it
				// arrives as TEXT and no script element is created.
				Assert.Equal ("<script>alert(1)</script>", await page.InnerTextAsync ("#encoded"));
				Assert.Equal (0, await page.Locator ("#encoded script").CountAsync ());
			}
		}

		[Fact]
		public async Task Posting_a_form_binds_the_model_and_redirects ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/");

				await page.FillAsync ("#message", "hello mvc");
				await page.RunAndWaitForNavigationAsync (async () => await page.ClickAsync ("#send"));

				// Html.BeginForm posted to /Home/Echo, the string bound, the action put it in TempData
				// and redirected - and TempData survived the redirect to be rendered by Index.
				Assert.EndsWith ("/", page.Url);
				Assert.Equal ("you said: hello mvc", await page.InnerTextAsync ("#echo"));
			}
		}

		[Fact]
		public async Task TempData_does_not_survive_a_second_request ()
		{
			var (context, page) = await fixture.NewPageAsync ();
			await using (context) {
				await page.GotoAsync ("/");
				await page.FillAsync ("#message", "one-shot");
				await page.RunAndWaitForNavigationAsync (async () => await page.ClickAsync ("#send"));

				Assert.Equal (1, await page.Locator ("#echo").CountAsync ());

				// TempData is read-once by design; a plain reload must not show it again.
				await page.GotoAsync ("/");

				Assert.Equal (0, await page.Locator ("#echo").CountAsync ());
			}
		}
	}
}
