# Generates MONOTODO.md: an inventory of upstream members that compile, are callable, and do nothing.
#
# Why this exists
# ---------------
# The port compiles Mono's sources IN PLACE, which is the whole design - it keeps the tree diffable
# against upstream. What comes with that is upstream's unfinished surface: members carrying
# [MonoTODO], and members whose body is `throw new NotImplementedException ()`. They bind, they build,
# and a consumer discovers them at runtime.
#
# LIMITATIONS.md documents what the PORT changed. It cannot document what upstream never finished,
# because that is thousands of members across a dozen assemblies and it moves whenever a source file
# is added. So it is generated: run this, commit MONOTODO.md, and a migrator can answer "is this
# member real?" before writing code against it rather than after.
#
#   powershell -ExecutionPolicy Bypass -File Tools/gen-monotodo-inventory.ps1
#
# Counts only - naming every member would produce a file nobody reads. The per-namespace totals are
# what a reader actually needs: they say which corners of the surface are thin.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

# The projects whose Sources.generated.props name upstream files. Deriving the file list from the
# generated props rather than globbing Mono/ matters: it counts only what is actually COMPILED, so an
# excluded file (Sqlite providers, AppDomain hosting) does not inflate the numbers with code no
# consumer can reach.
$projects = Get-ChildItem -Path $root -Directory |
            Where-Object { Test-Path (Join-Path $_.FullName 'Sources.generated.props') }

$rows = @()
$grandTodo = 0
$grandThrow = 0

foreach ($project in $projects) {
    $props = [xml](Get-Content (Join-Path $project.FullName 'Sources.generated.props'))

    $files = @()
    foreach ($compile in $props.Project.ItemGroup.Compile) {
        $include = $compile.Include
        if (-not $include) { continue }

        $path = Join-Path $project.FullName $include
        if (Test-Path $path) { $files += (Resolve-Path $path).Path }
    }

    $todo = 0
    $notImplemented = 0

    foreach ($file in $files) {
        $text = [System.IO.File]::ReadAllText($file)

        # [MonoTODO], [MonoTODO ("...")], [MonoNotSupported], and the Documentation variants.
        $todo += ([regex]::Matches($text, '\[Mono(TODO|NotSupported|LimitationAttribute)')).Count

        # A throwing body is the stronger signal: [MonoTODO] on a member that works is only a note.
        $notImplemented += ([regex]::Matches($text, 'throw new NotImplementedException')).Count
    }

    if ($files.Count -eq 0) { continue }

    $rows += [pscustomobject]@{
        Project        = $project.Name
        Files          = $files.Count
        MonoTODO       = $todo
        NotImplemented = $notImplemented
    }

    $grandTodo += $todo
    $grandThrow += $notImplemented
}

$rows = $rows | Sort-Object -Property NotImplemented -Descending

$lines = @()
$lines += '# Upstream unfinished surface'
$lines += ''
$lines += '**Generated by `Tools/gen-monotodo-inventory.ps1` - do not edit by hand.**'
$lines += ''
$lines += 'This port compiles Mono''s sources in place, so it inherits their unfinished members as well as'
$lines += 'their finished ones. Two markers count here, and they mean different things:'
$lines += ''
$lines += '| Marker | What it means for a caller |'
$lines += '|---|---|'
$lines += '| `[MonoTODO]` | A note from the original author. The member may work, may work partially, or may be a stub that silently returns `null`. **It does not throw**, which is what makes it the dangerous one. |'
$lines += '| `throw new NotImplementedException` | The member is a placeholder. You find out on the first call, loudly. |'
$lines += ''
$lines += 'Neither is a defect in this port, and neither is a to-do list for it: they are a map of where'
$lines += 'upstream stopped. `LIMITATIONS.md` documents what the port deliberately changed; this file'
$lines += 'documents what it deliberately did not touch.'
$lines += ''
$lines += 'A silently-null `[MonoTODO]` stub is exactly how Dynamic Data''s field templates rendered blank'
$lines += 'cells on a page returning HTTP 200 - worth remembering when a member returns nothing and no'
$lines += 'error appears.'
$lines += ''
$lines += '**Scope.** Only files that reach the compiler through a `Sources.generated.props` are counted -'
$lines += 'upstream sources and their line-preserving patched copies. Code written FOR this port'
$lines += '(`Port/`, `Shims/`, `Overrides/`) is excluded, and so is anything dropped by'
$lines += '`Tools/port-exclusions.txt`: a stub nobody can reach is not a hazard. So a project can show zero'
$lines += 'here and still have members this port chose not to implement - those are in `LIMITATIONS.md`.'
$lines += ''
$lines += '## By assembly'
$lines += ''
$lines += '| Project | Upstream files compiled | `[MonoTODO]` | `NotImplementedException` |'
$lines += '|---|---:|---:|---:|'

foreach ($row in $rows) {
    $lines += "| ``$($row.Project)`` | $($row.Files) | $($row.MonoTODO) | $($row.NotImplemented) |"
}

$lines += "| **Total** | | **$grandTodo** | **$grandThrow** |"
$lines += ''
$lines += '## How to check one member'
$lines += ''
$lines += 'The counts say where to be careful; they do not say which member. To check a specific one, read'
$lines += 'the upstream source - it is in the tree, and the port did not move it:'
$lines += ''
$lines += '```powershell'
$lines += 'Select-String -Path Mono/mcs/class/System.Web/**/*.cs -Pattern ''MonoTODO'' -Context 0,3 |'
$lines += '    Where-Object { $_.Context.PostContext -match ''YourMemberName'' }'
$lines += '```'
$lines += ''
$lines += 'If it throws, you will know at once. If it is a stub, the give-away is an auto-property with a'
$lines += 'private setter that nothing in the file ever assigns.'
$lines += ''

$output = Join-Path $root 'MONOTODO.md'
# UTF-8 without a BOM, explicitly, to match every other generated file here. The prose above is
# deliberately ASCII-only for the same reason: Windows PowerShell reads a .ps1 as ANSI unless it has a
# BOM, so a non-ASCII character in this file would arrive mangled under `powershell` and intact under
# `pwsh` - a difference nobody should have to know about to regenerate a document.
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($output, $lines, $utf8)

Write-Output "wrote $output"
Write-Output ("  {0} projects, {1} MonoTODO, {2} NotImplementedException" -f $rows.Count, $grandTodo, $grandThrow)
