<%@ Page Language="C#" %>
<%--
  LinqDataSource through a GridView - which is the only way anyone ever actually used it.

  ContextTypeName names the context by string, resolved through BuildManager, and TableName names a
  member on it. Where is the dynamic-query expression language: comparison, logical and arithmetic
  operators, member paths, literals and @parameters, and deliberately NO method calls. Parameter values
  are captured as constants and never re-parsed, so a query-string value containing "|| 1 == 1" is a
  value rather than a fragment of expression.
--%>
<!DOCTYPE html>
<html>
<head runat="server">
  <title>Products - LinqDataSource</title>
</head>
<body>
  <form id="form1" runat="server">

    <h1>Products</h1>

    <asp:LinqDataSource ID="ProductSource" runat="server"
                        ContextTypeName="DynamicDataSample.Models.ShopContext"
                        TableName="Products"
                        Where="Discontinued == false"
                        OrderBy="Name"
                        EnableUpdate="true"
                        EnableDelete="true" />

    <asp:GridView ID="ProductGrid" runat="server"
                  DataSourceID="ProductSource"
                  DataKeyNames="Id"
                  AutoGenerateColumns="false"
                  AutoGenerateEditButton="true"
                  AutoGenerateDeleteButton="true">
      <Columns>
        <asp:BoundField DataField="Id"    HeaderText="Id" ReadOnly="true" />
        <asp:BoundField DataField="Name"  HeaderText="Name" />
        <asp:BoundField DataField="Price" HeaderText="Price" DataFormatString="{0:0.00}" />
      </Columns>
    </asp:GridView>

    <h2>Filtered by category</h2>

    <!-- The same source with a parameter. QueryStringParameter feeds @Category; a request for
         Products.aspx?cat=2 shows only that category. -->
    <asp:LinqDataSource ID="CategorySource" runat="server"
                        ContextTypeName="DynamicDataSample.Models.ShopContext"
                        TableName="Products"
                        Where="CategoryId == @Category"
                        OrderBy="Price">
      <WhereParameters>
        <asp:QueryStringParameter Name="Category" QueryStringField="cat" Type="Int32" DefaultValue="1" />
      </WhereParameters>
    </asp:LinqDataSource>

    <asp:GridView ID="CategoryGrid" runat="server"
                  DataSourceID="CategorySource"
                  AutoGenerateColumns="false">
      <Columns>
        <asp:BoundField DataField="Name"  HeaderText="Name" />
        <asp:BoundField DataField="Price" HeaderText="Price" DataFormatString="{0:0.00}" />
      </Columns>
    </asp:GridView>

  </form>
</body>
</html>
