//------------------------------------------------------------------------------
// <auto-generated>
//     Control field declarations for Session.aspx.
//
//     The runtime generates its own partial from the markup; this one exists so the SDK build can
//     resolve the same names ahead of time, exactly as Visual Studio's designer always produced.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionStateSample
{
	public partial class SessionPage
	{
		protected global::System.Web.UI.WebControls.Literal Mode;
		protected global::System.Web.UI.WebControls.Literal Id;
		protected global::System.Web.UI.WebControls.Literal Result;
		protected global::System.Web.UI.WebControls.Literal Hits;
	}
}
